name: Deploy para EC2 via SCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copiar index.html via SCP para EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "index.html"
          target: "/home/ec2-user/"

      - name: Configurar sudo para ec2-user
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p 22 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo '${{ secrets.EC2_USER }} ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/${{ secrets.EC2_USER }}"

      - name: Mover index.html para /var/www/html
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p 22 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo mv /home/ec2-user/index.html /var/www/html/index.html"
